name: Rename CNAME

on:
  push:
    branches:
      - main

jobs:

  rename:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Rename CNAME.txt to CNAME
        run: |
          if [ -f CNAME.txt ] && [ ! -f CNAME ]; then
            mv CNAME.txt CNAME
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add CNAME.txt CNAME
            git commit -m "Rename CNAME.txt to CNAME"
            git push
          fi